### ISSUE TITLE
Clean up the Swagger doc

### ISSUE THREAD

**Issue by dpopp07** [bartop-io/bartop#121]
The Swagger doc is riddled with little validation errors and should be cleaned up. Additionally, the API route could be specified so that queries can be executed from the Swagger docs.

- [ ] Remove the validation errors
- [ ] Add correct API route
- [ ] Change README where it says "Documentation coming soon..."

**Comment by jamesvclements** [comment]
Can we close this since we're thoroughbred GraphQL now?

**Comment by dpopp07** [comment]
Just now seeing this comment ^ but ye
