### ISSUE TITLE
Set up a deploy of the development version of the app

### ISSUE THREAD

**Issue by dpopp07** [bartop-io/bartop#164]
We decided it would be a good idea to have the development version of the app running live, so it is easier to get UI/UX feedback from non-developers. We need to set up a deploy chain and publish to a cloud platform.

**Comment by jamesvclements** [comment]
Would be sick if we could have two dev environments besides prod using sub-domains:

`dev.bartop.io` -> merges to `master` auto-deploy here
`staging.bartop.io` -> we choose to release here, should be pretty much prod w/o prod data
`bartop.io` -> you already know ;)

This (likely) deserves it's own issue for DNS mapping & such

**Comment by jamesvclements** [comment]
I think this can be broken down more and added to the `App Deployment(s)` epic.

Something like:

* Explore hosting options
* Domain mapping
* DB deployments
* API server deployment
* UI server deployment
* Continuous delivery w/ Travis

**Comment by jamesvclements** [comment]
Closing this in favor of the [Epic](https://app.zenhub.com/workspace/o/dpopp07/bartop/issues/166)
