### ISSUE TITLE
Setup domain mapping for deployment environments

### ISSUE THREAD

**Issue by jamesvclements** [bartop-io/bartop#165]
* `dev.bartop.io` -> merges to `dev` auto-deploy here
* `staging.bartop.io` -> we choose to release here, should be pretty much prod w/o prod data
* `bartop.io` -> prod

**Comment by dpopp07** [comment]
What is the status on this?

**Comment by jamesvclements** [comment]
The UI is currently:

`dev.bartop.io` deployed from merges to `dev`
`bartop.io` deployed from merges to `prod`

we don't have staging yet, but we don't need it, so I think we can close this
