### ISSUE TITLE
Explore hosting options

### ISSUE THREAD

**Issue by jamesvclements** [bartop-io/bartop#167]
We need to host:

* the UI (CRA)
* the API (Express)
* the DB (RethinkDB)

There might be one platform that works great for all three, or not.

I don't know too much about this, but I think one option that could be relatively simple would be setting up a Kubernetes Cluster w/ each piece as an internal microservice. At which point we'd just be finding the best platform for hosting a Kube cluster.

Let's use this issue for the exploration, and then make new issue(s) for the implementation.

**Comment by dpopp07** [comment]
So hosting a Kube cluster for free is looking quite unlikely based on preliminary research. That being said, hosting some Docker containers is probably the best move here. Here are a couple options that I've read about as of now:
1. [Docker CE](https://www.docker.com/community-edition)
- Docker has it's own service for helping host Docker containers on other platforms. It is free for Open-Source

2. Hosting it ourselves (lol). Sounds jokey but [someone on Quora](https://www.quora.com/What-is-the-best-free-Docker-hosting) mentioned that it can sometimes be easier and get you more resources to run containers on an old computer of RasPi. I have both, so it could be a last-resort option.

**Comment by dpopp07** [comment]
Throwing some more links so I don't lose them
https://automationrhapsody.com/build-rest-api-express-node-js-run-docker/
https://hub.docker.com/_/rethinkdb/

**Comment by dpopp07** [comment]
> Let's use this issue for the exploration, and then make new issue(s) for the implementation.

It's been decided that we're using Netlify for the UI and GCP for the DB and API.
