### ISSUE TITLE
Deploy the UI w/ netlify

### ISSUE THREAD

**Issue by jamesvclements** [bartop-io/bartop#177]
[Netlify](https://www.netlify.com/) seems like a simple & sexy way to deploy the UI, so let's give it a try.

**Comment by dpopp07** [comment]
Guessing we will need to deploy API first so you know the URL to use? Will netlify support changing an env file without redeploying?

**Comment by jamesvclements** [comment]
We can add in `env` vars same way we do with Travis, and then just restart the deploy to update

**Comment by jamesvclements** [comment]
https://bartop-ui.netlify.com/

leggo
