### ISSUE TITLE
Pick hosting platform

### ISSUE THREAD

**Issue by jamesvclements** [bartop-io/bartop#43]
Options:
* AWS
* Google Cloud
* Heroku
* IBM Cloud ;) 
* other jawns

**Comment by jamesvclements** [comment]
We might be able to host the client server one place, and the api server elsewhere

**Comment by dpopp07** [comment]
Going with IBM Cloud for now

**Comment by jamesvclements** [comment]
^ **google cloud for the db & api, netlify for the ui
