### ISSUE TITLE
Handle starting server w/o running db more gracefully

### ISSUE THREAD

**Issue by jamesvclements** [bartop-io/bartop#51]
The server needs the db to run, as expected. But it's ugly:
![image](https://user-images.githubusercontent.com/20052710/33415174-7a1c9bc8-d55a-11e7-8efb-9c74ebe3542b.png)

Let's see if it could just say `hey, the server needs the db` or something along those lines

**Comment by dpopp07** [comment]
Well, I looked into trying to handle this just for fun and ran into this nice comment from the author of the module:
> No the driver doesn't bubble up these errors back to the user because there's nothing the user can do to handle them. The pool will automatically recover if RethinkDB is available again.

Pretty annoying but nothing I can really do about it. It'll have to be this way for now
