### ISSUE TITLE
Add slack channel & integration for new user sign-up

### ISSUE THREAD

**Issue by jamesvclements** [bartop-io/bartop#62]
While reading the Auth0 docs for Hooks so we can save new users to our DB, I noticed that a neat use case is adding a Slack integration so that we're notified when new users sign-up. That'd be sick. Here's the docs:

https://auth0.com/docs/hooks/extensibility-points/post-user-registration

**Comment by dpopp07** [comment]
You did this right? Shall we close this issue?

**Comment by jamesvclements** [comment]
Yep yep
