### ISSUE TITLE
Document some examples of awesome native mobile sign-up / logins

### ISSUE THREAD

**Issue by jamesvclements** [bartop-io/bartop#97]
A good first step to locking in our sign-up flow (particularly the UX / UI) would to be collect a couple great mobile app examples. I say mobile, because BarTop is mobile-first, but these sign-up experience could be from anywhere. My previously mentioned examples are RobinHood & AirBnB. If we could add GIFs, screenshots, or some kind of visual representation of the examples that'd be neat.

As it stands, our current flow is

1. User presses sign up
2. Redirected to Auth0's hosted login
3. User enters email address
4. User receives email with verification code
5. User navigates back to login page (after checking email), and enters their code
6. User is signed-up

Notes:
1. We want to use SMS verification instead of email, but we're still trying to figure out a way around Twilio's less than generous free tier.

2. This is just our first shot at a flow. It doesn't include the actual UX details or UI that can make it a smooth process. Plus we need also need to be asking for the user's full name.

**Comment by dpopp07** [comment]
- As soon as I read the title of the issue, before reading your post, I thought of AirBnb. One of my favorite sign up experiences of all time.
- RobinHood is nice too but I think takes a bit long with the amount of stuff they ask you.
- I think Slack does a nice job with their mobile sign up as well.  

These are some examples, I agree we could put together a little portfolio of screenshots, etc. pretty easily. I'll bet @haleygreene09 has some examples of stuff she's liked as well.

**Comment by haleygreene09** [comment]
By native do you mean native app? Or do you solely want to look at mobile
web experiences? Bc those are different

**Comment by jamesvclements** [comment]
@haleygreene09 Native mobile like iOS / Android applications. We can look at mobile web, but we're trying to be as similar to native apps so I think focusing on those for inspiration is our best bet

**Comment by dpopp07** [comment]
https://www.useronboard.com/

**Comment by jamesvclements** [comment]
^ truth
